base: base_link
left_front:
  - lf_hip
  - lf_leg
  - lf_lowleg
  - lf_foot

right_front:
  - rf_hip
  - rf_leg
  - rf_lowleg
  - rf_foot

left_hind:
  - lh_hip
  - lh_leg
  - lh_lowleg
  - lh_foot

right_hind:
  - rh_hip
  - rh_leg
  - rh_lowleg
  - rh_foot